spring:
  application:
    name: tj-spring-cloud-config
  cloud:
    config:
      label: master #仓库
      server:
        git:
          uri: https://github.com/SIR-TJ/itoken.git
          search-paths: itoken-config/respo
          username:
          password:

server:
  port: 8888 #默认8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/